import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import AxeBuilder from '@axe-core/playwright';

test('search, sample pages and row scope preserve the complete exported counts', async ({ page, context }, testInfo) => {
  await page.goto('/'); await expect(page.getByRole('status')).toContainText('Listo');
  await context.setOffline(true);
  const text = 'timestamp,energy_kWh\n' + Array.from({ length: 61 }, (_, i) => `${new Date(Date.UTC(2024, 0, 1) + i * 3600000).toISOString()},${i === 60 ? '1' : ''}`).join('\n');
  await page.locator('#file').setInputFiles({ name: 'many-missing.csv', mimeType: 'text/csv', buffer: Buffer.from(text) });
  await expect(page.getByRole('status')).toContainText('Archivo leído');
  await page.getByLabel('Tipo de medición').selectOption('counter');
  await page.getByLabel('Separador decimal').selectOption('.');
  await page.getByLabel('He revisado').check(); await page.getByRole('button', { name: 'Analizar archivo' }).click();
  await page.getByLabel('Buscar regla o descripción').fill('value_missing');
  await expect(page.locator('.finding')).toHaveCount(1);
  await page.locator('.finding').click();
  await expect(page.locator('#detail')).toContainText('60 incidencias en total · 50 ejemplos guardados');
  await expect(page.locator('#sample-page table')).toHaveCount(5);
  await expect(page.locator('#sample-page')).toContainText('Registros 2');
  await page.getByRole('button', { name: 'Ejemplos siguientes' }).focus(); await page.keyboard.press('Enter');
  await expect(page.locator('#detail')).toContainText('Página 2 de 10');
  await expect(page.locator('#sample-page')).toContainText('Registros 7');
  for (let i = 0; i < 8; i++) await page.getByRole('button', { name: 'Ejemplos siguientes' }).click();
  await expect(page.getByRole('button', { name: 'Ejemplos siguientes' })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Ejemplos anteriores' })).toBeFocused();
  await expect(page.locator('#sample-page')).toContainText('Registros 51');
  await page.getByRole('button', { name: 'Volver al hallazgo' }).click();
  await expect(page.locator('.finding')).toBeFocused();
  await page.getByLabel('Fila CSV en las muestras').fill('8'); await page.locator('.finding').click();
  await expect(page.locator('#sample-page table')).toHaveCount(1);
  await expect(page.locator('#sample-page')).toContainText('Registros 8');
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]);
  await page.locator('.findings-panel').screenshot({ path: testInfo.outputPath('finding-navigation.png') });
  await page.getByLabel('Fila CSV en las muestras').fill('55');
  await expect(page.locator('#findings')).toContainText('Una fila sin muestras no demuestra');
  const downloading = page.waitForEvent('download'); await page.getByRole('button', { name: 'Descargar JSON' }).click();
  const file = await downloading; const report = JSON.parse(await readFile((await file.path())!, 'utf8'));
  expect(report.findings.find((f: { code: string }) => f.code === 'VALUE_MISSING').count).toBe(60);
  await page.getByRole('button', { name: 'Limpiar filtros' }).click();
  await expect(page.getByLabel('Buscar regla o descripción')).toBeFocused();
  await expect(page.getByLabel('Fila CSV en las muestras')).toHaveValue('');
  await page.setViewportSize({ width: 320, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('real battery file exposes missing values through the browser worker', async ({ page }) => {
  await page.goto('/');
  await page.locator('#file').setInputFiles('examples/real/bateria-inicio-registro.csv');
  await expect(page.getByRole('status')).toContainText('Archivo leído');
  await page.locator('#timestamp').selectOption('0'); await page.locator('#value').selectOption('1');
  await page.getByLabel('Tipo de medición').selectOption('counter');
  await page.getByLabel('Unidad', { exact: true }).selectOption('kWh');
  await page.getByLabel('Separador decimal').selectOption('.');
  await page.getByLabel('Cadencia esperada (min)', { exact: true }).fill('60');
  await page.getByLabel('He revisado').check(); await page.getByRole('button', { name: 'Analizar archivo' }).click();
  await expect(page.locator('#completeness-explanation')).toContainText('153 / 192 (79,6875 %)');
  await page.getByRole('button', { name: /VALUE_MISSING/ }).click();
  await expect(page.locator('#detail')).toContainText('39 incidencias en total · 39 ejemplos guardados');
  await expect(page.locator('#sample-page table')).toHaveCount(5);
});
